### ISSUE TITLE
Add a switch to zip files instead of always zipping...

### ISSUE THREAD

**Issue by alpakeno** [mmozeiko/pkg2zip#1]

**Comment by mmozeiko** [comment]
I want to keep my NoNpDrm dumps as one file. It's easier to manage storage this way. It's also faster to copy it around, instead of sometimes hundreds if not thousands of small files. And it gives you automatic checksums, so you can later detect if file is corrupted. Zip file it creates is not compressed, it uses "store" method, because almost all files are encrypted anyway  so there is no performance penalty of creating zip file - only advantages (performance, checksums, accidentally deleting some files).

**Comment by alpakeno** [comment]
yeah, but this way it's the same as the vpk which will take double space when transferring and installing it in PSVita, also each PKG has it's own sha1 checksum so you can check if it's corrupted.
Thx for the tool :)

**Comment by chronoss09** [comment]
Why not creat a simply folder of game without zip file ?

**Comment by mmozeiko** [comment]
@alpakeno You don't need to transfer zip file. Open it up in your favorite archiver program, or even Windows Explorer, and then drag&drop files to connected Vita device. Or if you use command-line - cd to vita drive/mounted folder and execute "unzip path/to/file.zip".

Yes, pkg has checksum, but after it is unpacked, there are not checksum.

@chronoss09 because of reasons I mentioned above.

**Comment by chronoss09** [comment]
Ok thanks !

**Comment by noX1609** [comment]
So one question: Does the tool create a zip file out of the pkg or does it extract the files in a folder atm? That‘s not clear to me. 
And would it be ok for you (the creator) if i use the shell script to create a Gui Version for macOS? I can share it with you if you want to :)

Thanks in advice for an answer to my questions :)

**Comment by mmozeiko** [comment]
It creates zip file out of files that are extracted from contents of pkg file. pkg itself doesn't contain zip file, although its structure is very similar to zip files.

How can you use shell script to create GUI? Do you mean TUI?
You can create whatever you want based on my tool, but I'm not sure if I want non-crossplatform code back in my repo...
